all: 1 2

1: task1.c
	cc -Wall -Wextra -Weverything -Wpedantic -std=c99 task1.c -o task1.bin

2: task2.c
	cc -Wall -Wextra -Weverything -Wpedantic -std=c99 task2.c -o task2.bin

clean:
	rm -f task1.bin task2.bin
